### ISSUE TITLE
SCRIPT FOR USERINFO

### ISSUE THREAD

**Issue by gzepeda09** [namesEd/Team-Ramrod#75]
Ed please write a script that will return me all the info from the user that is not data-sensitive

**Comment by namesEd** [comment]
This is the current table for the users, I will send everything other than the password. 
TABLE `users` (                                                                                                     
  `userID` int(15) NOT NULL AUTO_INCREMENT,                                                                                          
  `first_name` varchar(100) NOT NULL,                                                                                                
  `last_name` varchar(100) NOT NULL,                                                                                                 
  `email` varchar(100) NOT NULL,                                                                                                     
  `username` varchar(100) NOT NULL,                                                                                                  
  `password` varchar(100) NOT NULL,                                                                                                  
  `birthday` date DEFAULT NULL,
  `isVendor` ENUM('yes', 'no') DEFAULT 'no'

**Comment by namesEd** [comment]
get_user_data.php should meet the needs, lmk
